"""Added User columns

Revision ID: c24d5dcd56db
Revises: b8cc249b1a82
Create Date: 2023-06-07 18:18:11.655189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24d5dcd56db'
down_revision = 'b8cc249b1a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birthday')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
